apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: example-fft-job
  namespace: research
spec:
  minAvailable: 9
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - name: "main"
      replicas: 1
      template:
        metadata:
          name: finetune
        spec:
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 100Gi
            - name: basemodel
              hostPath:
                path: /home/bmm-system/data/system/models/chatglm-130b-v0.8.6-raw
                type: Directory
            - name: rawdataset
              hostPath:
                path: /data/glusterfs/liusong/dataset-files
                type: Directory
            - name: output
              hostPath:
                path: /data/glusterfs/liusong/experiments/example-01/
                type: DirectoryOrCreate
          containers:
            - name: main
              image: a100-harbor.bigmodel.cn/maas/bmm-chatglm-130b:train-20230720175103
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities:
                  add:
                  - IPC_LOCK
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: basemodel
                  mountPath: /data/basemodel
                - name: rawdataset
                  mountPath: /data/rawdataset
                - name: output
                  mountPath: /data/output
              env:
                - name: ENV_RAW_DATASET_PATH
                  value: /data/rawdataset/example/data.json
                - name: ENV_INPUT_CKPT_PATH
                  value: /data/basemodel
                - name: ENV_INPUT_DATASET_PATH
                  value: /data/output/dataset
                - name: ENV_OUTPUT_BASE_PATH
                  value: /data/output
                - name: ENV_OUTPUT_CKPT_PATH
                  value: /data/output/ckpts
                - name: ENV_OUTPUT_TB_PATH
                  value: /data/output/tb
                - name: ENV_OUTPUT_LOG_PATH
                  value: /data/output/log
                - name: ENV_NUM_WORKERS
                  value: "8"
                - name: ENV_TRAIN_TOKENS
                  value: "10000000"
                - name: ENV_GLOBAL_BATCH_SIZE
                  value: "64"
              args:
                - --hostenvs
                - VC_MAIN_HOSTS
                - VC_WORKER_HOSTS
                - --commands
                - "python3 data/process_sft.py --data_path ${ENV_RAW_DATASET_PATH} --output_dir ${ENV_INPUT_DATASET_PATH}/train"
                - "bash scripts/submit_gpu.sh configs/glm-130b/glm-130b-sft.sh"
              resources:
                requests:
                  nvidia.com/gpu: 8
                  rdma/shared_ibs: 1
                limits:
                  nvidia.com/gpu: 8
                  rdma/shared_ibs: 1
          restartPolicy: OnFailure
    - name: "worker"
      replicas: 7
      template:
        metadata:
          name: finetune
        spec:
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 100Gi
            - name: basemodel
              hostPath:
                path: /home/bmm-system/data/system/models/chatglm-130b-v0.8.6-raw
                type: Directory
            - name: rawdataset
              hostPath:
                path: /data/glusterfs/liusong/dataset-files
                type: Directory
            - name: output
              hostPath:
                path: /data/glusterfs/liusong/experiments/example-01/
                type: DirectoryOrCreate
          containers:
            - name: worker
              image: a100-harbor.bigmodel.cn/maas/bmm-chatglm-130b:train-20230720175103
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities:
                  add:
                  - IPC_LOCK
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: basemodel
                  mountPath: /data/basemodel
                - name: rawdataset
                  mountPath: /data/rawdataset
                - name: output
                  mountPath: /data/output
              env:
                - name: ENV_INPUT_CKPT_PATH
                  value: /data/basemodel
                - name: ENV_INPUT_DATASET_PATH
                  value: /data/output/dataset
                - name: ENV_OUTPUT_BASE_PATH
                  value: /data/output
                - name: ENV_OUTPUT_CKPT_PATH
                  value: /data/output/ckpts
                - name: ENV_OUTPUT_TB_PATH
                  value: /data/output/tb
                - name: ENV_OUTPUT_LOG_PATH
                  value: /data/output/log
                - name: ENV_NUM_WORKERS
                  value: "8"
                - name: ENV_TRAIN_TOKENS
                  value: "10000000"
                - name: ENV_GLOBAL_BATCH_SIZE
                  value: "64"
              command: ["/bin/sh"]
              args: ["-c", "mkdir -p /var/run/sshd && /usr/sbin/sshd -D"]
              resources:
                requests:
                  nvidia.com/gpu: 8
                  rdma/shared_ibs: 1
                limits:
                  nvidia.com/gpu: 8
                  rdma/shared_ibs: 1
          restartPolicy: OnFailure
    - name: "agent"
      replicas: 1
      template:
        metadata:
          name: finetune
        spec:
          volumes:
            - name: output
              hostPath:
                path: /data/glusterfs/liusong/experiments/example-01/
                type: DirectoryOrCreate
          containers:
            - name: agent
              image: nginx
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: output
                  mountPath: /data/output
              env:
                - name: ENV_OUTPUT_BASE_PATH
                  value: /data/output
                - name: ENV_OUTPUT_CKPT_PATH
                  value: /data/output/ckpts
                - name: ENV_OUTPUT_TB_PATH
                  value: /data/output/tb
                - name: ENV_OUTPUT_LOG_PATH
                  value: /data/output/log
              resources:
                requests:
                  cpu: "4"
          restartPolicy: OnFailure